n_steps: &n_steps 12
val_n_steps: *n_steps
env_name: &env_name visual-antmaze-medium-v0

base_lr: 0.001
data:
  dataset_type: DatasetType.LocoMaze
  d4rl_config:
    env_name: *env_name
    random_actions: false
    img_size: 64
    alpha: 0.6
    batch_size: 128
    beta: 0.4
    crop_length: null
    path: /vast/wz1232/ogbench/visual_ant_maze_medium_explore_5M_noise1/train
    location_only: false
    normalize: true
    num_workers: 10
    prioritized: false
    quick_debug: false
    n_steps: *n_steps
    seed: 0
    stack_states: 3
    train: true
    val_fraction: 0.2
epochs: 4
eval_at_beginning: false
eval_during_training: true
eval_every_n_epochs: 2
eval_mpcs: 20
eval_only: false
hjepa:
  l1_n_steps: *n_steps
  train_l1: true
  freeze_l1: false
  disable_l2: true
  level1:
    backbone:
      arch: resnet18
      backbone_mlp: null
      backbone_width_factor: 2
      input_dim: 4
      channels: 9
      final_ln: true
    predictor:
      predictor_arch: rnnV2
      rnn_converter_arch: ''
      rnn_layers: 2
      rnn_state_dim: 512
      z_dim: 0
      z_min_std: 0.1
      predictor_ln: false
      tie_backbone_ln: true
    use_z_goal: false
    action_dim: 8
    momentum: 0
  step_skip: 4
load_checkpoint_path: null
load_l1_only: false
objectives_l1:
  idm:
    action_dim: 8
    coeff: 0.49214
    arch: '256'
  kl:
    global_coeff: 1
    global_prior: true
  objectives:
  - ObjectiveType.VICReg
  - ObjectiveType.IDM
  prediction:
    global_coeff: 1
  vicreg:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 2.4075
    cov_coeff_t: 0
    projector: id
    random_projector: false
    sim_coeff: 10
    std_coeff: 0.93183
    std_coeff_t: 0.24353
optimizer_type: Adam
output_dir: test
output_root: /scratch/wz1232/HJEPA/checkpoint/visual_antmaze
eval_cfg:
  env_name: *env_name
  log_heatmap: false
  eval_l1: true
  probing:
    l1_depth: 20
    train_path: /vast/wz1232/ogbench/visual_ant_maze_medium_explore_5M_noise0/train
    val_path: /vast/wz1232/ogbench/visual_ant_maze_medium_explore_5M_noise0/val_50000
    probe_targets: 'locations,proprio_vel,proprio_pos'
    locations: 
      arch: '256-128'
    proprio_vel:
      arch: '256-128'
    proprio_pos:
      arch: '256-128'
    probe_mpc: false
    probe_wall: false
    probe_encoder: false
    probe_preds: true
    epochs: 5
    epochs_enc: 5
    epochs_latent: 5
    full_finetune: false
    lr: 0.0008
    max_samples: 2000000
    max_samples_enc: 2000000
    schedule: Cosine
    visualize_probing: true
    load_prober: false
  d4rl_planning:
    n_envs: 40
    n_envs_batch_size: 20
    n_steps: 40
    level: "medium"
    eval_all_levels: false
    log_pred_dist_every: 9999999
    plot_every: 2
    img_size: 64
    replan_every: 2
    image_obs: true
    stack_states: 3
    set_full_states: true
    data_path: "/vast/wz1232/ogbench/visual_ant_maze_medium_stitch_1M_noise0.2/val_50000"
    level1:
      planner_type: PlannerType.MPPI
      min_step: 0
      max_step: 1
      clamp_actions: true
      max_plan_length: 16
      mppi:
        noise_sigma: 5
        num_samples: 500
        lambda_: 0.0025
quick_debug: false
run_group: vc-maze-uniform-image-stack2_seed=246_env_medium
run_name: vc-maze-uniform-image-stack2_seed=246_env_medium_seed=3_v2
run_project: HJEPA-visual-antmaze
save_every_n_epochs: 1
seed: 246
wandb: true
