n_steps: &n_steps 15
val_n_steps: *n_steps
env_name: &env_name maze2d_medium_diverse

base_lr: 0.030745
data:
  dataset_type: DatasetType.D4RL
  d4rl_config:
    env_name: *env_name
    random_actions: false
    img_size: 81
    alpha: 0.6
    batch_size: 128
    beta: 0.4
    crop_length: null
    images_path: /vast/wz1232/maze2d_medium_diverse/images.npy
    path: /vast/wz1232/maze2d_medium_diverse/data.p
    location_only: false
    normalize: true
    num_workers: 10
    prioritized: false
    quick_debug: false
    n_steps: *n_steps
    seed: 0
    stack_states: 1
    train: true
    val_fraction: 0.2
epochs: 3
eval_at_beginning: false
eval_during_training: false
eval_every_n_epochs: 1
eval_mpcs: 20
eval_only: false
hjepa:
  l1_n_steps: *n_steps
  train_l1: true
  freeze_l1: false
  disable_l2: true
  level1:
    backbone:
      arch: menet6
      backbone_subclass: d4rl_a
      backbone_mlp: null
      backbone_width_factor: 2
      input_dim: 4
      channels: 3
      proprio_dim: 2
      late_fuse_proprio_encoder_arch: 'id'
    predictor:
      residual: true
      action_encoder_arch: 'id'
      predictor_arch: conv2
      predictor_subclass: d4rl_b_p
      rnn_converter_arch: ''
      rnn_layers: 1
      rnn_state_dim: 512
      z_dim: 0
      z_min_std: 0.1
    encode_only: false
    use_z_goal: false
    action_dim: 2
    momentum: 0
  step_skip: 4
load_checkpoint_path: null
load_l1_only: false
objectives_l1:
  idm:
    action_dim: 2
    coeff: 3.348
    arch: 'conv'
    use_pred: false
    arch_subclass: a
  kl:
    global_coeff: 1
    global_prior: true
  laplacian:
    c: 1
    detach_predictor: true
    discount: 0.9
    generalized: false
    generalized_coeff_bias: 0
    generalized_coeff_curve: 0
    generalized_negative: false
    global_coeff: 1
    negative_coeff: 1
    negative_one_step: false
    p1_correction: false
    p2_correction: false
    predictor_coeff: 0
    projector: id
    random_projector: false
    reg: 0
    remove_d: false
    split_batch: false
  objectives:
  - ObjectiveType.VICRegObs
  - ObjectiveType.IDM
  - ObjectiveType.PredictionProprio
  prediction:
    global_coeff: 0.48455
  probe:
    coeff: 1
    arch_subclass: 'b'
  reconstruction:
    channels: 1
    decoder_arch: menet5
    img_size: 28
    plot_every: 50000
    pred_coeff: 1
    rec_coeff: 1
    target_repr_dim: null
    width_factor: 1
  vicreg_obs:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 26.178
    cov_coeff_t: 0
    cov_per_feature: false
    projector: id
    random_projector: false
    sim_coeff: 1
    std_coeff: 32.145
    std_coeff_t: 1.8662
optimizer_type: Adam
output_dir: maze2d_medium_diverse
output_root: /scratch/wz1232/HJEPA/checkpoint/maze2d_medium_diverse
eval_cfg:
  env_name: *env_name
  log_heatmap: false
  eval_l1: true
  probing:
    l1_depth: *n_steps
    train_images_path: /vast/wz1232/maze2d_medium_diverse_probe/images_train.npy
    train_path: /vast/wz1232/maze2d_medium_diverse_probe/data_train.p
    val_images_path: /vast/wz1232/maze2d_medium_diverse_probe/images_val.npy
    val_path: /vast/wz1232/maze2d_medium_diverse_probe/data_val.p
    probe_targets: 'locations,proprio_vel'
    locations:
      arch: 'conv'
      subclass: 'c'
    proprio_vel:
      arch: 'conv'
      subclass: 'c'
    l2_probe_targets: 'locations'
    probe_mpc: false
    probe_wall: false
    probe_proprio: true
    probe_encoder: false
    probe_preds: true
    epochs: 5
    epochs_enc: 5
    epochs_latent: 5
    full_finetune: false
    lr: 0.0032
    max_samples: 2000000
    max_samples_enc: 2000000
    schedule: Cosine
    visualize_probing: true
    load_prober: false
  d4rl_planning:
    n_envs: 85
    n_envs_batch_size: 16
    n_steps: 192
    levels: "easy,medium,hard"
    easy:
      n_steps: 192
      n_envs: 40
      max_plan_length: 128
      plot_every: 16
      min_block_radius: -1
      max_block_radius: 3
      override_config: true
    medium:
      n_steps: 192
      n_envs: 40
      max_plan_length: 128
      plot_every: 16
      min_block_radius: 4
      max_block_radius: 6
      override_config: true
    hard:
      n_steps: 192
      n_envs: 40
      max_plan_length: 128
      plot_every: 16
      min_block_radius: 7
      max_block_radius: 99999
      override_config: true
    log_pred_dist_every: 9999999
    plot_every: 16
    set_start_target_path: ""
    action_repeat: 4
    action_repeat_mode: 'null'
    img_size: 81
    replan_every: 4
    image_obs: true
    stack_states: 1
    data_path: '/vast/wz1232/maze2d_medium_diverse'
    level1:
      planner_type: PlannerType.MPPI
      min_step: 0
      max_step: 1
      max_plan_length: 128
      sgd:
        action_change_reg: 0
        l2_reg: 0
        lr: 0.03
        n_iters: 200
      mppi:
        noise_sigma: 5
        num_samples: 500
        lambda_: 0.0025
    #d4rl specific
    level: "random" # easy, medium, hard, random
    position_only: true
quick_debug: false
run_group: vc-maze-uniform-image-stack2_seed=246_env_medium
run_name: vc-maze-uniform-image-stack2_seed=246_env_medium_seed=3_v2
run_project: HJEPA-maze
save_every_n_epochs: 1
seed: 246
wandb: true
