n_steps: &n_steps 17
val_n_steps: *n_steps
env_name: wall

base_lr: 0.001
dataset_type: DatasetType.Wall
dot_config:
  action_bias_only: false
  action_noise: 1
  batch_size: 128
  device: cuda
  dot_std: 1.3
  img_size: 28
  max_step: 1
  n_steps: *n_steps
  noise: 0
  normalize: true
  size: 10000
  static_noise: 0
  static_noise_speed: 0
  structured_noise: false
  structured_noise_path: /tmp/cifar10
  train: true
  zero_action: false
  repeat_actions: 1
epochs: 100
eval_at_beginning: false
eval_during_training: false
eval_mpcs: 20
eval_only: false
hjepa:
  train_l1: true
  freeze_l1: false
  disable_l2: true
  level1:
    action_dim: 2
    backbone_arch: kevnet
    backbone_mlp: null
    backbone_width_factor: 2
    input_dim: null
    momentum: 0
    n_channels: 2
    predictor_arch: conv2
    repr_dim: 8192
    rnn_layers: 1
    z_dim: 0
    z_min_std: 0.1
  level2:
    action_dim: 0
    backbone_arch: ''
    backbone_mlp: null
    backbone_width_factor: 2
    input_dim: 512
    momentum: 0
    n_channels: 1
    predictor_arch: rnnV2
    repr_dim: 256
    rnn_layers: 1
    z_dim: 16
    z_min_std: 0.1
  step_skip: 4
load_checkpoint_path: null
load_l1_only: false
log_heatmap: false
objectives_l1:
  idm:
    action_dim: 2
    coeff: 1
    repr_dim: 8192
  kl:
    global_coeff: 1
    global_prior: true
    repr_dim: 512
  laplacian:
    c: 1
    detach_predictor: true
    discount: 0.9
    generalized: false
    global_coeff: 1
    negative_coeff: 1
    predictor_coeff: 0
    projector: id
    random_projector: false
    reg: 0
    remove_d: false
    repr_dim: 512
    split_batch: false
  objectives:
  - ObjectiveType.VICReg
  - ObjectiveType.IDM
  reconstruction:
    channels: 1
    decoder_arch: menet5
    img_size: 28
    plot_every: 50000
    pred_coeff: 1
    rec_coeff: 1
    repr_dim: 512
    target_repr_dim: null
    width_factor: 1
  vicreg:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 1
    cov_coeff_t: 0
    projector: 'id'
    random_projector: false
    repr_dim: 8192
    sim_coeff: 1
    std_coeff: 0.1
    std_coeff_t: 0.1
    std_margin: 1
    std_margin_t: 1
objectives_l2:
  idm:
    action_dim: 2
    coeff: 1
    repr_dim: 512
  kl:
    global_coeff: 1
    global_prior: true
    repr_dim: 512
  laplacian:
    c: 1
    detach_predictor: true
    discount: 0.9
    generalized: false
    global_coeff: 1
    negative_coeff: 1
    predictor_coeff: 0
    projector: id
    random_projector: false
    reg: 0
    remove_d: false
    repr_dim: 512
    split_batch: false
  objectives: []
  reconstruction:
    channels: 1
    decoder_arch: menet5
    img_size: 28
    plot_every: 50000
    pred_coeff: 1
    rec_coeff: 1
    repr_dim: 512
    target_repr_dim: null
    width_factor: 1
  vicreg:
    adjust_cov: false
    cov_chunk_size: null
    cov_coeff: 1
    cov_coeff_t: 0
    projector: id
    random_projector: false
    repr_dim: 512
    sim_coeff: 25
    std_coeff: 25
    std_coeff_t: 0
optimizer_type: Adam
output_dir: test
output_root: /scratch/wz1232/HJEPA/checkpoint
wall_planning:
  fix_wall: true
  lr: 0.22
  max_plan_length: 44
  max_step: 2.45
  min_step: 0.27
  n_envs: 300
  n_iters: 400
  n_steps: 44
  repr_target: true
  seed: 42
  loss_coeff_first: 0.1
  loss_coeff_last: 1
  sum_all_diffs: false
  wall_padding: 3
  start_ends_grid: false
  early_stop: -1
  early_stop_perc: 0.001
probe_latents: false
probe_mpc: false
probe_wall: true
probing_cfg:
  epochs: 30
  epochs_enc: 30
  epochs_latent: 5
  full_finetune: false
  lr: 0.001
  probe_targets: "locations"
  locations:
    arch: ''
  schedule: null
  l1_depth: *n_steps
quick_debug: false
run_name: test
run_project: HJEPA-wall
safe_every_n_epochs: 10
seed: 1
wall_config:
  action_bias_only: false
  action_noise: 1
  action_angle_noise: 0.2
  action_step_mean: 1.0
  action_step_std: 0.4
  action_lower_bd: 0.2
  action_upper_bd: 1.8
  batch_size: 64
  device: cuda
  dot_std: 1.3
  fix_wall_batch_k: null
  fix_wall: true
  fix_door_location: 10
  fix_wall_location: 32
  wall_padding: 20
  door_padding: 10
  num_train_layouts: -1
  
  img_size: 64
  max_step: 1
  n_steps: *n_steps
  n_steps_reduce_factor: 1
  noise: 0
  normalize: true
  size: 10000
  static_noise: 0
  static_noise_speed: 0
  structured_noise: false
  structured_noise_path: /tmp/cifar10
  train: true
  zero_action: false
  repeat_actions: 1
wandb: true
