n_steps: &n_steps 61
l1_n_steps: &l1_n_steps 15
val_n_steps: *n_steps
l2_step_skip: &l2_step_skip 6
env_name: &env_name wall

base_lr: 0.0021
l1_to_l2_lr_ratio: 0.09
data:
  dataset_type: DatasetType.Wall
  dot_config:
    action_bias_only: false
    action_noise: 1
    batch_size: 128
    device: cuda
    dot_std: 1.3
    img_size: 28
    max_step: 1
    n_steps: *n_steps
    noise: 0
    normalize: true
    l2_step_skip: *l2_step_skip
    size: 10000
    static_noise: 0
    static_noise_speed: 0
    structured_noise: false
    structured_noise_path: /tmp/cifar10
    train: true
    zero_action: false
    repeat_actions: 1
    border_wall_loc: 5
  wall_config:
    action_bias_only: false
    action_noise: 1
    action_angle_noise: 0.1
    action_step_mean: 1.0
    action_step_std: 0.4
    action_lower_bd: 0.2
    action_upper_bd: 1.8
    action_param_xy: true
    l2_step_skip: *l2_step_skip
    batch_size: 64
    device: cuda
    dot_std: 1.3
    border_wall_loc: 5
    fix_wall_batch_k: null
    fix_wall: false
    fix_door_location: 10
    fix_wall_location: 32
    exclude_wall_train: ''
    exclude_door_train: ''
    only_wall_val: ''
    only_door_val: ''
    wall_padding: 20
    door_padding: 10
    wall_width: 3
    door_space: 4
    num_train_layouts: -1
    cross_wall_rate: 0.08
    expert_cross_wall_rate: 0
    expert_action_step_mean: 0.9
    expert_action_step_std: 0
    expert_action_lower_bd: 0.9
    expert_action_upper_bd: 0.9
    expert_traj_door_padding: 1.8
    img_size: 65
    max_step: 1
    n_steps: *n_steps
    n_steps_reduce_factor: 1
    noise: 0
    normalize: true
    size: 20000
    val_size: 10000
    static_noise: 0
    static_noise_speed: 0
    structured_noise: false
    structured_noise_path: /tmp/cifar10
    train: true
    zero_action: false
    repeat_actions: 1
epochs: 100
eval_at_beginning: false
eval_during_training: false
eval_mpcs: 20
eval_only: false
hjepa:
  l1_n_steps: *l1_n_steps
  train_l1: true
  freeze_l1: false
  disable_l2: false
  step_skip: *l2_step_skip
  correct_l2_merge: true
  level1:
    backbone:
      arch: menet6
      backbone_subclass: i
      backbone_mlp: null
      backbone_norm: group_norm #group_norm, batch_norm
      backbone_pool: dim_reduce #dim_reduce, avg_pool
      backbone_final_fc: false
      backbone_width_factor: 2
      input_dim: null
      fc_output_dim: null
      channels: 2
    predictor:
      predictor_arch: conv2
      rnn_layers: 1
      z_dim: 0
      z_min_std: 0.1
    action_dim: 2
    momentum: 0
  level2:
    backbone:
      arch: 'menet6'
      backbone_subclass: l2b
      backbone_width_factor: 2
      backbone_mlp: null
      channels: 2
      input_dim: 512
      fc_output_dim: null
    predictor:
      predictor_arch: conv2
      predictor_subclass: a
      rnn_state_dim: 512
      rnn_converter_arch: ''
      z_dim: 0
      z_min_std: 0.1
      posterior_drop_p: 0.25
      rnn_layers: 1
    action_dim: 2
    momentum: 0.0
    use_z_goal: false
load_checkpoint_path: null
load_l1_only: false
objectives_l1:
  idm:
    action_dim: 2
    coeff: 2.1
    arch: '512'
  kl:
    global_coeff: 1
    global_prior: true
  objectives:
  - ObjectiveType.VICReg
  - ObjectiveType.IDM
  reconstruction:
    channels: 1
    decoder_arch: menet5
    img_size: 28
    plot_every: 50000
    pred_coeff: 1
    rec_coeff: 1
    target_repr_dim: null
    width_factor: 1
  vicreg:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 4.6
    cov_coeff_t: 0
    projector: 'id'
    random_projector: false
    sim_coeff: 1
    std_coeff: 3.9
    std_coeff_t: 0.26
    std_margin: 1
    std_margin_t: 1
objectives_l2:
  idm:
    action_dim: 2
    coeff: 0
    arch: "512"
  kl:
    global_coeff: 1
    global_prior: true
  objectives:
    - VICReg
  reconstruction:
    channels: 1
    decoder_arch: menet5
    img_size: 28
    plot_every: 50000
    pred_coeff: 1
    rec_coeff: 1
    target_repr_dim: null
    width_factor: 1
  vicreg:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 12
    cov_coeff_t: 0.43
    projector: 'id'
    random_projector: false
    sim_coeff: 1
    std_coeff: 2.1
    std_coeff_t: 0.71
    std_margin: 1
    std_margin_t: 1
optimizer_type: Adam
output_dir: test
output_root: /scratch/wz1232/HJEPA/checkpoint
eval_cfg:
  env_name: *env_name
  eval_l1: false
  log_heatmap: false
  h_wall_planning:
    n_envs: 300
    n_steps: 96
    final_trans_norm_cutoff: 4
    final_trans_steps: 15
    mock_l1: false # use 1/l2_step_skip if set to true
    use_memory: false
    memory_diff_threshold: 31
    n_envs_batch_size: 200
    seed: 42
    error_threshold: 1.0
    levels: "medium"
    level1:
      planner_type: PlannerType.SGD
      min_step: 0
      max_step: 2.45
      repr_target: true
      sum_all_diffs: true
      loss_coeff_first: 1
      loss_coeff_last: 1
      sgd:
        lr: 0.3
        n_iters: 100
    level2:
      planner_type: PlannerType.MPPI
      min_step: 0
      max_step: 2.1
      min_plan_length: 3 #
      max_plan_length: 16 #
      repr_target: true
      sum_all_diffs: false
      depth_probe_threshold: 25
      probe_depth: false
      sum_last_n: 3
      sgd:
        lr: 0.3
        n_iters: 450
      mppi:
        noise_sigma: 5
        num_samples: 500
        lambda_: 0.005
      lfgbs:
        history_size: 10
        max_iter: 20
  probing:
    probe_mpc: false
    probe_encoder: false
    probe_wall: true
    epochs: 20
    epochs_enc: 30
    epochs_latent: 5
    full_finetune: false
    lr: 0.0002
    probe_targets: "locations"
    locations:
      arch: '512'
    schedule: Constant
    l1_depth: *l1_n_steps
    l2_depth: *n_steps
    sample_timesteps: 30
quick_debug: false
run_name: test
run_project: HJEPA-wall
seed: 1
wandb: true
