env: ant_medium_diverse
num_blocks_width_in_img: 10
n_episodes: 500
train_maps_n: 20
episode_length: 500 
img_size: [64, 64, 3]
qvel_norm_prior: false 
action_repeat: 1
action_repeat_mode: id 
resample_every: 20
action_noise: 0
sampling_mode: uniform
max_path_len: 12
sparsity_low: 50 
sparsity_high: 80
ogbench_gather: True
dataset_type: explore2
noise: 0.5
expert_restore_path: /scratch/wz1232/ogbench/data_gen_scripts/experts/ant
expert_restore_epoch: 400000
seed: 0
render: True
no_legs: True